#!/bin/sh

echo Finding current directory...
cd "$(dirname "$0")"

FILE='ardublock-all-withNewPing.jar'
USERS=$(dscl . list /Users | grep -vE '^_|dameon|nobody|root')
if test -f "./$FILE" ; then
    for u in $USERS; do
        echo "Copying $FILE to /Users/$u/Documents/Arduino/tools/ArduBlockTool/tool..."
        sudo mkdir -p /Users/$u/Documents/Arduino/tools/ArduBlockTool/tool
        sudo cp ./$FILE  /Users/$u/Documents/Arduino/tools/ArduBlockTool/tool/
    done
else
    echo "$FILE does not exist"
fi

LIB='NewPing'
if test -d "./$LIB" ; then
    echo "Installing $LIB Library to /Applications/Arduino/libraries"
    sudo mkdir -p /Applications/Arduino/libraries
    sudo cp -r ./$LIB /Applications/Arduino/libraries/
else
    echo "$LIB does not exist"
fi

DRIVERZIP='CH34x_Install_V1.3.zip'
DRIVER='ch34x_install_v1.3.pkg'
if test -f "./$DRIVERZIP"; then
    echo "CH34x Driver exists"
    echo "Running install"
    unzip $DRIVERZIP 
    #open $DRIVER
    sudo installer -verbose -allowUntrusted -pkg $DRIVER -target /
else
    echo "$DRIVERZIP does not exist"
fi