#!/bin/sh

echo Finding current directory...
cd "$(dirname "$0")"

FILE='ardublock-all-withNewPing.jar'
if test -f "./$FILE" ; then
    echo "Copying $FILE to /Applications/Arduino/tools/ArduBlockTool/tool..."
    mkdir -p /Applications/Arduino/tools/ArduBlockTool/tool
    cp ./$FILE /Applications/Arduino/tools/ArduBlockTool/tool/
else
    echo "$FILE does not exist"
fi

LIB='NewPing'
if test -d "./$LIB" ; then
    echo "Installing $LIB Library to /Applications/Arduino/libraries"
    mkdir -p /Applications/Arduino/libraries
    cp -r ./$LIB /Applications/Arduino/libraries/
else
    echo "$LIB does not exist"
fi

DRIVERZIP='CH34x_Install_V1.3.zip'
DRIVER='ch34x_install_v1.3.pkg'
if test -f "./$DRIVERZIP"; then
    echo "CH34x Driver exists"
    echo "Running install"
    unzip $DRIVERZIP 
    open $DRIVER
    #sudo installer -allowUntrusted -pkg $DRIVER -target /
else
    echo "$DRIVERZIP does not exist"
fi









