#!/bin/sh
### Thanks to https://grahamrpugh.com/2017/01/07/application-to-run-shell-commands-with-admin-rights.html
### Script designed to be placed in a "Run Shell Script" action in Automator
### This allows the administrator password to be called, and used in the script where sudo is required
### Beware: the inputted password is used in echo commands
### Usage: Use `sudo` without a path to ensure the `sudo` function is called rather than the actual command

# Dialog Title
dialogTitle="Ardublock and CH34x Installer"

# obtain the password from a dialog box
authPass=$(/usr/bin/osascript <<EOT
tell application "System Events"
    activate
    repeat
        display dialog "Please enter your Apple ID password to start software installation." ¬
            default answer "" ¬
            with title "$dialogTitle" ¬
            with hidden answer ¬
            buttons {"Quit", "Continue"} default button 2
        if button returned of the result is "Quit" then
            return 1
            exit repeat
        else if the button returned of the result is "Continue" then
            set pswd to text returned of the result
            set usr to short user name of (system info)
            try
                do shell script "echo test" user name usr password pswd with administrator privileges
                return pswd
                exit repeat
            end try
        end if
        end repeat
        end tell
EOT
)

# Abort if the Quit button was pressed
if [ "$authPass" == 1 ]; then
    /bin/echo "User aborted. Exiting..."
    exit 0
fi

# function that replaces sudo command
sudo () {
    /bin/echo $authPass | /usr/bin/sudo -S "$@"
}

echo "\n************************************"
echo "\nBarnabas Ardublock and CH34x Driver Beginning...\n"
echo Finding current directory...
cd "$(dirname "$0")"

FILE='ardublock-all-withNewPing.jar'
USERS=$(dscl . list /Users | grep -vE '^_|daemon|nobody|root')
if test -f "./$FILE" ; then
    for u in $USERS; do
        echo "\nCopying $FILE to /Users/$u/Documents/Arduino/tools/ArduBlockTool/tool..."
        sudo mkdir -p /Users/$u/Documents/Arduino/tools/ArduBlockTool/tool
        sudo cp ./$FILE  /Users/$u/Documents/Arduino/tools/ArduBlockTool/tool/
    done
else
    echo "$FILE does not exist"
fi

LIB='NewPing'
if test -d "./$LIB" ; then
    echo "\nInstalling $LIB Library to /Applications/Arduino/libraries"
    sudo mkdir -p /Applications/Arduino/libraries
    sudo cp -r ./$LIB /Applications/Arduino/libraries/
else
    echo "$LIB does not exist"
fi

DRIVERZIP='CH34x_Install_V1.3.zip'
DRIVER='ch34x_install_v1.3.pkg'
if test -f "./$DRIVER"; then
#   echo "CH34x Driver exists"
    echo "\nRunning install"
#    chmod +x $DRIVERZIP
#    ./$DRIVERZIP
#    unzip $DRIVERZIP
#     chmod +x $DRIVER
#     ./$DRIVER
    # open $DRIVER
    sudo installer -verboseR -allowUntrusted -pkg $DRIVER -target /
else
    echo "$DRIVERZIP does not exist"
fi

reStart=$(/usr/bin/osascript <<EOT
tell application "System Events"
    activate
        display dialog "Installation complete! Click 'Restart' to reboot your computer. This must be done before trying to connect to your Barnabas hardware." ¬
            with title "$dialogTitle" ¬
            buttons {"Restart", "Later"} default button 1
        if button returned of the result is "Restart" then
            return 1
        else if the button returned of the result is "Later" then
            return 0
        end if
        end tell
EOT
)

# reboot if selected
if [ "$reStart" == 1 ]; then
    sudo reboot
    exit 0
fi


